Repository vrk-kpa/suomifi-design-tokens, pull requests merged in 2019-10, with the labels that each got.

#7 Add tokens actionElementInnerText, actionElementInnerTextSmallScreen,…
  src/tokens.json
Labels: enhancement

#8 Release 0.1.0
  package.json
Labels: release

#11 WIP: Font family export formatting fixes
  README.md
  src/convert.js
  src/interfaces.ts.template
  src/tokens.json
Labels: bug

#13 Release 0.2.0
  package.json
Labels: release
