Repository vrk-kpa/suomifi-design-tokens, pull requests merged in 2020-03, with the labels that each got.

#29 [Bugfix]Rename depthLight4 to depthDark1
  src/tokens.json
Labels: bug

#30 Raise version to 0.7.1
  package.json
Labels: release

#31 [Bugfix] Update all dependencies to latest available version.
  package.json
  yarn.lock
Labels: bug

#32 [Release] 0.7.2
  package.json
Labels: release

#33 [Feature] Spacings to use 5px series
  src/tokens.json
  yarn.lock
Labels: enhancement

#34 [Release] 0.8.0
  package.json
Labels: bug, enhancement
